[32mINFO    [0m integration.test_trust:test_trust.py:75 Connection attempt failed: (0)
Reason: Handshake status 500 Internal Server Error -+-+- {'audit-id': 'd2365c9d-4a47-4ce9-8f18-3740f60d2c6f', 'cache-control': 'no-cache, private', 'content-type': 'application/json', 'warning': '299 - "Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens."', 'date': 'Fri, 20 Sep 2024 01:33:15 GMT', 'content-length': '170'} -+-+- b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error dialing backend: dial tcp 10.1.0.103:10250: connect: connection refused","code":500}\n'

[32mINFO    [0m integration.test_trust:test_trust.py:77 Retrying (1/20)...
[32mINFO    [0m integration.test_trust:test_trust.py:72 Connection established: <class 'juju.client._definitions.FullStatus'>({'applications': {}, 'branches': {}, 'controller_timestamp': '2024-09-20T01:33:19.098659383Z', 'filesystems': [], 'machines': {}, 'model': <class 'juju.client._definitions.ModelStatusInfo'>({'available_version': '', 'cloud_tag': 'cloud-microk8s', 'meter_status': <class 'juju.client._definitions.MeterStatus'>({'color': '', 'message': '', 'unknown_fields': {}}), 'model_status': <class 'juju.client._definitions.DetailedStatus'>({'data': {}, 'err': None, 'info': '', 'kind': '', 'life': '', 'since': '2024-09-20T01:32:31.132763161Z', 'status': 'available', 'version': '', 'unknown_fields': {}}), 'name': 'test', 'region': 'localhost', 'sla': 'unsupported', 'type_': 'caas', 'version': '3.4.4', 'unknown_fields': {}}), 'offers': {}, 'relations': [], 'remote_applications': {}, 'storage': [], 'volumes': [], 'unknown_fields': {}})